const CANCIONES = [
    { titulo: "Blitzkrieg Bop", artista: "Ramones", year: 1976, spotifyId: "4KcH1ZRV2W1q7Flq0QqC76" },
    { titulo: "En algún lugar", artista: "Duncan Dhu", year: 1987, spotifyId: "3UIENhLRdFIOuRan92cAQu" },
    { titulo: "One More Time", artista: "Daft Punk", year: 2001, spotifyId: "2Uy6EhQXAYkXA6MohPgjpV" },
    { titulo: "México Lindo y Querido", artista: "Jorge Negrete", year: 1952, spotifyId: "567aGQVtUEhNuDpp9Dtewp" },
    { titulo: "Tequila", artista: "The Champs", year: 1958, spotifyId: "5gJKsGij5oGt5H5RSFYXPa" },
    { titulo: "Regalo de Dios", artista: "Julión Alvares y su Norteño Banda", year: 2023, spotifyId: "51qYdMBxt9mFbtZBzq1Yfi" },
    { titulo: "Oblivion", artista: "Grimes", year: 2012, spotifyId: "4BY4V1T0RJK1HmD2Q0ClyK" },
    { titulo: "Piano Man", artista: "Billy Joel", year: 1973, spotifyId: "78WVLOP9pN0G3gRLFy1rAa" },
    { titulo: "We Own the Night", artista: "Dance Gavin Dance", year: 2015, spotifyId: "7xCcUcMcGsIYGKUVgBZUw5" },
    { titulo: "Contrabando y Traición", artista: "Los Tigres del Norte", year: 1974, spotifyId: "4gRi0itWso2UodoRMP5asJ" },
    { titulo: "Manic Monday", artista: "The Bangles", year: 1985, spotifyId: "798fUF6UnRn27xiVuKyJCi" },
    { titulo: "Callaita", artista: "Bad Bunny", year: 2019, spotifyId: "2TH65lNHgvLxCKXM3apjxI" },
    { titulo: "Nube Viajera", artista: "Alejandro Fernández", year: 1996, spotifyId: "7qOjjzbvSsdHcAU31va4rz" },
    { titulo: "I Will Wait", artista: "Mumford & Sons", year: 2012, spotifyId: "0hm8rgOY17z7kQJlqGKbu7" },
    { titulo: "Vuela, Vuela (Voyage, Voyage)", artista: "Magneto", year: 2007, spotifyId: "6nz1ojKuYx5HO7Vh0wmuWp" },
    { titulo: "Te Sigo Amando", artista: "Juan Gabriel", year: 1980, spotifyId: "3Bn5su26JosHjkbIrxgz0j" },
    { titulo: "Someone You Loved", artista: "Lewis Capaldi", year: 2018, spotifyId: "2TIlqbIneP0ZY1O0EzYLlc" },
    { titulo: "Autos, Moda Y Rock N Roll", artista: "Fandango", year: 1987, spotifyId: "5JiRlyOGE2EYvzLyex6pdK" },
    { titulo: "Bazar", artista: "Flans", year: 1985, spotifyId: "7CLxH03q65I3aktL79k4vE" },
    { titulo: "Africa", artista: "TOTO", year: 1982, spotifyId: "2374M0fQpWi3dLnB54qaLX" },
    { titulo: "Jamás", artista: "Camilo Sesto", year: 1975, spotifyId: "0ScrUVrcTYIZijbqDZ3CJE" },
    { titulo: "Cielito Lindo", artista: "Darvelio Arredondo", year: 2022, spotifyId: "0d3QIQcaCHdt9aJlRQlOpE" },
    { titulo: "Ginza", artista: "J Balvin", year: 2016, spotifyId: "2C2TGgFzrTRIOdQS1vUN5h" },
    { titulo: "Quevedo: Bzrp Music Sessions, Vol. 52/66", artista: "Bizarrap", year: 2022, spotifyId: "2tTmW7RDtMQtBk7m2rYeSw" },
    { titulo: "Al Final", artista: "Emmanuel", year: 1988, spotifyId: "3yeT1oIBRGuEhOb3OCvL2z" },
    { titulo: "La Mordidita (feat. Yotuel)", artista: "Ricky Martin", year: 2015, spotifyId: "00i0O74dXdaKKdCrqHnfXm" },
    { titulo: "Beat It", artista: "Michael Jackson", year: 2008, spotifyId: "1OOtq8tRnDM8kG2gqUPjAj" },
    { titulo: "Siempre Tuya Desde La Raíz", artista: "Paulina Rubio", year: 1996, spotifyId: "7yXXFYlLaA2cjcbnij7e5h" },
    { titulo: "Firework", artista: "Katy Perry", year: 2010, spotifyId: "1mXuMM6zjPgjL4asbBsgnt" },
    { titulo: "Vivir Mi Vida", artista: "Marc Anthony", year: 2013, spotifyId: "3QHMxEOAGD51PDlbFPHLyJ" },
    { titulo: "Sweet Child O' Mine", artista: "Guns N' Roses", year: 1987, spotifyId: "7o2CTH4ctstm8TNelqjb51" },
    { titulo: "Oops!...I Did It Again", artista: "Britney Spears", year: 2000, spotifyId: "6naxalmIoLFWR0siv8dnQQ" },
    { titulo: "Ni Lo Intentes", artista: "Julión Álvarez y su Norteño Banda", year: 2010, spotifyId: "3WiU6ZeOD7UFjTSPraQMPl" },
    { titulo: "Mi Pueblo", artista: "Cesar Costa", year: 2008, spotifyId: "3SSOvO40lo6wmz8r0Kt3M1" },
    { titulo: "Walk This Way", artista: "Aerosmith", year: 1975, spotifyId: "5SZ6zX4rOrEQferfFC2MfP" },
    { titulo: "It's My Life", artista: "Bon Jovi", year: 2010, spotifyId: "6iNBM60VQtPUUhkKfwa5KV" },
    { titulo: "Mientes", artista: "Camila", year: 2010, spotifyId: "5EhzE6HJaCcLFrf5rPqvpk" },
    { titulo: "Tú Y Yo Somos Uno Mismo", artista: "Timbiriche", year: 1988, spotifyId: "1K7bwHdwsTjt9YiNmiib0P" },
    { titulo: "Mío", artista: "Paulina Rubio", year: 1992, spotifyId: "77GJz1FIKgjIp9KtnGc8Fl" },
    { titulo: "Todo Cambió", artista: "Camila", year: 2006, spotifyId: "4OyzSXRSadNQt5EMwASdap" },
    { titulo: "Smoke Gets In Your Eyes", artista: "The Platters", year: 1986, spotifyId: "57yz5oqMytzbwdewSG28L9" },
    { titulo: "You Sexy Thing - Single Version", artista: "Hot Chocolate", year: 2007, spotifyId: "3jAG0kb7gg0vGeFFZj6bBt" },
    { titulo: "Let It Be - Remastered 2009", artista: "The Beatles", year: 1970, spotifyId: "7iN1s7xHE4ifF5povM6A48" },
    { titulo: "You Get What You Give", artista: "New Radicals", year: 1998, spotifyId: "1Cwsd5xI8CajJz795oy4XF" },
    { titulo: "(I've Had) The Time of My Life - From \"Dirty Dancing\" Soundtrack", artista: "Bill Medley", year: 2009, spotifyId: "1UvTPXlImVd4jcucK4qJwb" },
    { titulo: "Amiga mía", artista: "Alejandro Sanz", year: 1997, spotifyId: "6kQYMqjobmB8MkWwa9OUyA" },
    { titulo: "Querida", artista: "Juan Gabriel", year: 1984, spotifyId: "5ySxlyvySBhIEvoO2xx7uT" },
    { titulo: "Never Gonna Give You Up", artista: "Rick Astley", year: 1987, spotifyId: "4cOdK2wGLETKBW3PvgPWqT" },
    { titulo: "Felices los 4", artista: "Maluma", year: 2018, spotifyId: "1RouRzlg8OKFeqc6LvdxmB" },
    { titulo: "Twist And Shout", artista: "The Isley Brothers", year: 2005, spotifyId: "7iFdUmdqT9XrsJdSGf9KrX" },
    { titulo: "No One", artista: "Alicia Keys", year: 2007, spotifyId: "6IwKcFdiRQZOWeYNhUiWIv" },
    { titulo: "Media Vuelta", artista: "José Alfredo Jimenez", year: 1970, spotifyId: "0QvxVQaOUIMgqxyvk9GpFE" },
    { titulo: "No Podras", artista: "Cristian Castro", year: 1992, spotifyId: "6ZIwZmQ2ph6QK13sItmDEx" },
    { titulo: "Shake It Off", artista: "Taylor Swift", year: 2014, spotifyId: "5xTtaWoae3wi06K5WfVUUH" },
    { titulo: "Amigo", artista: "Roberto Carlos", year: 2003, spotifyId: "24Thqkee9KZgifP7G8c70N" },
    { titulo: "Te Vi", artista: "Piso 21", year: 2018, spotifyId: "059bcIhyc2SBwm6sw2AZzd" },
    { titulo: "Hollaback Girl", artista: "Gwen Stefani", year: 2004, spotifyId: "0LzrhCZFXW94Y8nwtTuRlw" },
    { titulo: "Volver, Volver", artista: "Vicente Fernández", year: 1972, spotifyId: "4Fvnz1ZJ86IdqDAepWYPAh" },
    { titulo: "Andar Conmigo", artista: "Julieta Venegas", year: 2003, spotifyId: "05iMQqncVBIm4AE26EvaTL" },
    { titulo: "American Pie", artista: "Don McLean", year: 1971, spotifyId: "1fDsrQ23eTAVFElUMaf38X" },
    { titulo: "Ni tú ni nadie", artista: "Alaska Y Dinarama", year: 1984, spotifyId: "7LpS82vPDLgZAHWRtWBBRj" },
    { titulo: "El Final", artista: "Rostros Ocultos", year: 2017, spotifyId: "39ELDQVDsgBmo5gbTuru9U" },
    { titulo: "Blurred Lines", artista: "Robin Thicke", year: 2020, spotifyId: "2pgbGOb00WrlXY3ZRFKn7v" },
    { titulo: "I Like You (A Happier Song) (with Doja Cat)", artista: "Post Malone", year: 2022, spotifyId: "0O6u0VJ46W86TxN9wgyqDj" },
    { titulo: "All I Wanna Do Is Make Love To You", artista: "Heart", year: 1990, spotifyId: "5YjKdeES9QRJ8NmF4Xc8pV" },
    { titulo: "La Pachanga", artista: "Vilma Palma e Vampiros", year: 1991, spotifyId: "1x6bkwDyWIOZNFY5blRSs1" },
    { titulo: "Thinking out Loud", artista: "Ed Sheeran", year: 2014, spotifyId: "34gCuhDGsG4bRPIf9bb02f" },
    { titulo: "Poker Face", artista: "Lady Gaga", year: 2008, spotifyId: "5R8dQOPq8haW94K7mgERlO" },
    { titulo: "Fireflies", artista: "Owl City", year: 2009, spotifyId: "3DamFFqW32WihKkTVlwTYQ" },
    { titulo: "Jump", artista: "Van Halen", year: 1996, spotifyId: "6Fba9RZtC6vTY814JToDtP" },
    { titulo: "Eternamente Bella", artista: "Alejandra Guzman", year: 1996, spotifyId: "3pIgumKqXX7ge7lT9rCvNy" },
    { titulo: "You're Beautiful", artista: "James Blunt", year: 2005, spotifyId: "0vg4WnUWvze6pBOJDTq99k" },
    { titulo: "I Gotta Feeling", artista: "Black Eyed Peas", year: 2009, spotifyId: "2H1047e0oMSj10dgp7p2VG" },
    { titulo: "La Muralla Verde", artista: "Los Enanitos Verdes", year: 1986, spotifyId: "6OKhBvddAlWxxFnjbpilhu" },
    { titulo: "Say So", artista: "Doja Cat", year: 2019, spotifyId: "3Dv1eDb0MEgF93GpLXlucZ" },
    { titulo: "Ironic - 2015 Remaster", artista: "Alanis Morissette", year: 1995, spotifyId: "1d6KS9GH06JAd19uiBy9IE" },
    { titulo: "With Or Without You", artista: "U2", year: 1998, spotifyId: "1Og8U5KRel9D51h4bmznlE" },
    { titulo: "I Like To Move It (feat. The Mad Stuntman) - Erick \"More\" Album Mix", artista: "Reel 2 Real", year: 1994, spotifyId: "6dHTkQYY3zdR9i9Nj0IGVW" },
    { titulo: "Heaven", artista: "Bryan Adams", year: 1984, spotifyId: "7Ewz6bJ97vUqk5HdkvguFQ" },
    { titulo: "Soak Up The Sun", artista: "Sheryl Crow", year: 2002, spotifyId: "215JYyyUnrJ98NK3KEwu6d" },
    { titulo: "Rayando el Sol", artista: "Maná", year: 1990, spotifyId: "4Ofg5uuH7qqDIXpAJMpXZV" },
    { titulo: "It Wasn't Me", artista: "Shaggy", year: 2000, spotifyId: "3WkibOpDF7cQ5xntM1epyf" },
    { titulo: "Usted", artista: "Los Tres Diamantes", year: 1971, spotifyId: "1Wt3vmlSvvdyjeizfXsyrg" },
    { titulo: "Start Me Up - Remastered 2009", artista: "The Rolling Stones", year: 1981, spotifyId: "7HKez549fwJQDzx3zLjHKC" },
    { titulo: "Runaway Train", artista: "Soul Asylum", year: 2000, spotifyId: "3Ib3SJV8ZXuLvDiDb2w1As" },
    { titulo: "Verónica", artista: "Victor Yturbe \"El Piruli\"", year: 2001, spotifyId: "0TwbY0aX7jIgJLFXZCUcti" },
    { titulo: "¿Cómo Pagarte?", artista: "Carlos Rivera", year: 2016, spotifyId: "7kkJnzW5TlGwzYYcps0Qv9" },
    { titulo: "Lo Dudo", artista: "José José", year: 1985, spotifyId: "65vU70CBDU0sQDfOWkwUEH" },
    { titulo: "Si No Te Hubieras Ido", artista: "Marco Antonio Solís", year: 2011, spotifyId: "3l1ZanpJ3jFQZMqATizqfE" },
    { titulo: "Provócame", artista: "Chayanne", year: 1992, spotifyId: "3mbQd1v6N7nqX2mcAyCxCU" },
    { titulo: "Persiana Americana - Remasterizado 2007", artista: "Soda Stereo", year: 1986, spotifyId: "71awpJoi5bqGMBrTkHDDoL" },
    { titulo: "Girls Just Want to Have Fun", artista: "Cyndi Lauper", year: 1983, spotifyId: "4y1LsJpmMti1PfRQV9AWWe" },
    { titulo: "Crazy In Love (feat. JAY-Z)", artista: "Beyoncé", year: 2003, spotifyId: "5IVuqXILoxVWvWEPm82Jxr" },
    { titulo: "Thunderstruck", artista: "AC/DC", year: 1990, spotifyId: "57bgtoPSgt236HzfBOd8kj" },
    { titulo: "I Got You Babe", artista: "Sonny & Cher", year: 1965, spotifyId: "4SGBuq37Ol4HJr7pQqFMKa" },
    { titulo: "Sweet Home Alabama", artista: "Lynyrd Skynyrd", year: 1974, spotifyId: "7e89621JPkKaeDSTQ3avtg" },
    { titulo: "drivers license", artista: "Olivia Rodrigo", year: 2021, spotifyId: "5wANPM4fQCJwkGd4rN57mH" },
    { titulo: "Cruz de navajas", artista: "Mecano", year: 1986, spotifyId: "6VWWU8EFSS7Xx1TZ830Paz" },
    { titulo: "I Will Always Love You", artista: "Whitney Houston", year: 1992, spotifyId: "4eHbdreAnSOrDDsFfc4Fpm" },
    { titulo: "Right Here Waiting", artista: "Richard Marx", year: 1989, spotifyId: "4LFwNJWoj74Yd71fIr1W8x" },
    { titulo: "December, 1963 (Oh What a Night!)", artista: "The Four Seasons", year: 1975, spotifyId: "1hQFF33xi8ruavZNyovtUN" },
    { titulo: "Hey Ya!", artista: "Outkast", year: 2003, spotifyId: "2PpruBYCo4H7WOBJ7Q2EwM" },
    { titulo: "Sweet Dreams (Are Made of This) - 2005 Remaster", artista: "Eurythmics", year: 1983, spotifyId: "6oWLiyRpo1ibp2vKNxHG0T" },
    { titulo: "Yeah! (feat. Lil Jon & Ludacris)", artista: "USHER", year: 2004, spotifyId: "5rb9QrpfcKFHM1EUbSIurX" },
    { titulo: "Tacones Rojos", artista: "Sebastian Yatra", year: 2021, spotifyId: "0Be7sopyKMv8Y8npsUkax2" },
    { titulo: "Si Nos Dejan", artista: "José Alfredo Jimenez", year: 2000, spotifyId: "1mTWvb5uY8R6tU7iCLtiUo" },
    { titulo: "That's Amore", artista: "Dean Martin", year: 2009, spotifyId: "6GYqOflskcZxPj8rkTZkOy" },
    { titulo: "Mírame a los Ojos", artista: "Onda Vaselina", year: 1998, spotifyId: "0q3P0vjpqqswJSukITnfZA" },
    { titulo: "Entre dos tierras", artista: "Heroes Del Silencio", year: 1990, spotifyId: "4rJdaSwOCHLBhxdMsymeMw" },
    { titulo: "I Want It That Way", artista: "Backstreet Boys", year: 1999, spotifyId: "47BBI51FKFwOMlIiX6m8ya" },
    { titulo: "Somos Novios", artista: "Armando Manzanero", year: 1990, spotifyId: "05CfvXFk8iDBJpxYHi8Kpq" },
    { titulo: "The Look", artista: "Roxette", year: 1988, spotifyId: "2oWMI54r0qT4N8Xb4C76vq" },
    { titulo: "Counting Stars", artista: "OneRepublic", year: 2013, spotifyId: "2tpWsVSb9UEmDRxAl1zhX1" },
    { titulo: "Barbie Girl", artista: "Aqua", year: 1997, spotifyId: "5ZrDlcxIDZyjOzHdYW1ydr" },
    { titulo: "Give A Little Bit", artista: "Supertramp", year: 1977, spotifyId: "6XUHsYE38CEbYunT983O9G" },
    { titulo: "Smells Like Teen Spirit", artista: "Nirvana", year: 1991, spotifyId: "4CeeEOM32jQcH3eN9Q2dGj" },
    { titulo: "Bule Bule", artista: "Los Rockin' Devils", year: 2004, spotifyId: "19Ol3nKQvIJJiKBTIOBzwi" },
    { titulo: "Escape (The Pina Colada Song)", artista: "Rupert Holmes", year: 1979, spotifyId: "5IMtdHjJ1OtkxbGe4zfUxQ" },
    { titulo: "Dance Monkey", artista: "Tones And I", year: 2019, spotifyId: "5ZULALImTm80tzUbYQYM9d" },
    { titulo: "I Got You (I Feel Good)", artista: "James Brown & The Famous Flames", year: 1966, spotifyId: "5haXbSJqjjM0TCJ5XkfEaC" },
    { titulo: "Ya Me Enteré", artista: "Reik", year: 2016, spotifyId: "0lPXFrKyl8HkdQ2E6NmNja" },
    { titulo: "No Volvere", artista: "Miguel Aceves Mejia", year: 2001, spotifyId: "31FSxMxEOyc9kzz3Mdmvlz" },
    { titulo: "Solamente una Vez", artista: "Agustín Lara", year: 2011, spotifyId: "3KXT4z3ZtA8yasFoqltxzP" },
    { titulo: "Hips Don't Lie (feat. Wyclef Jean)", artista: "Shakira", year: 2005, spotifyId: "3ZFTkvIE7kyPt6Nu3PEa7V" },
    { titulo: "Solo Se Vive una Vez", artista: "Monica Naranjo", year: 1994, spotifyId: "2e7mL0M7mvjYVANfWPUjCH" },
    { titulo: "La Niña Fresa", artista: "Banda Zeta", year: 1994, spotifyId: "3sgHiiSR5V8V97FiQtne0u" },
    { titulo: "Me Rehúso", artista: "Danny Ocean", year: 2019, spotifyId: "6ifUES3keWjwXgae8pXI3o" },
    { titulo: "I'm a Believer - 2006 Remaster", artista: "The Monkees", year: 1967, spotifyId: "3G7tRC24Uh09Hmp1KZ7LQ2" },
    { titulo: "Dejame Entrar", artista: "Mœnia", year: 1997, spotifyId: "3c1JleEU920IOWJCdqRW0n" },
    { titulo: "Gangsta's Paradise", artista: "Coolio", year: 1995, spotifyId: "1DIXPcTDzTj8ZMHt3PDt8p" },
    { titulo: "Light My Fire", artista: "The Doors", year: 1967, spotifyId: "5uvosCdMlFdTXhoazkTI5R" },
    { titulo: "Jailhouse Rock", artista: "Elvis Presley", year: 1958, spotifyId: "4gphxUgq0JSFv2BCLhNDiE" },
    { titulo: "Propuesta Indecente", artista: "Romeo Santos", year: 2014, spotifyId: "5PycBIeabfvX3n9ILG7Vrv" },
    { titulo: "Cada Que...", artista: "Belanova", year: 2007, spotifyId: "1IDfAcL63xIRjG4Q98yTfn" },
    { titulo: "Closer", artista: "The Chainsmokers", year: 2016, spotifyId: "7BKLCZ1jbUBVqRi2FVlTVw" },
    { titulo: "Crank That (Soulja Boy)", artista: "Soulja Boy", year: 2007, spotifyId: "66TRwr5uJwPt15mfFkzhbi" },
    { titulo: "La Sirenita", artista: "Rigo Tovar", year: 1976, spotifyId: "6X2Mxz4KnWYOAOHmv3MNAK" },
    { titulo: "If You Leave Me Now", artista: "Chicago", year: 1976, spotifyId: "0KMGxYKeUzK9wc5DZCt3HT" },
    { titulo: "Paradise By the Dashboard Light", artista: "Meat Loaf", year: 1977, spotifyId: "2g7gviEeJr6pyxO7G35EWQ" },
    { titulo: "You Can't Hurry Love", artista: "The Supremes", year: 1966, spotifyId: "4H1iMlEWKZmpKTHCZzDhju" },
    { titulo: "Se Te Olvida (La Mentira)", artista: "Javier Solís", year: 1963, spotifyId: "0TUtx6LilxwUOtZJKikydZ" },
    { titulo: "Celebration", artista: "Kool & The Gang", year: 1980, spotifyId: "3K7Q9PHUWPTaknlbFPThn2" },
    { titulo: "Take A Chance On Me", artista: "ABBA", year: 1977, spotifyId: "5BckPAYcKEJuYs1eV1BHHe" },
    { titulo: "Because of You", artista: "Kelly Clarkson", year: 2004, spotifyId: "0gJvqi9QyASOCtJu99tytc" },
    { titulo: "Vive", artista: "José Maria Napoleón", year: 1976, spotifyId: "4YTsQ1axezXF9S6DmX45LS" },
    { titulo: "¿Donde Están?", artista: "Sentidos Opuestos", year: 1997, spotifyId: "4svFtvFAitlF833rgaDW22" },
    { titulo: "La de la Mochila Azul", artista: "Pedrito Fernández", year: 1978, spotifyId: "7n1KtrkdGQb2kEOj0M8zVR" },
    { titulo: "Hey, Soul Sister", artista: "Train", year: 2010, spotifyId: "4HlFJV71xXKIGcU3kRyttv" },
    { titulo: "Another Brick in the Wall, Pt. 2", artista: "Pink Floyd", year: 1979, spotifyId: "4gMgiXfqyzZLMhsksGmbQV" },
    { titulo: "Le Freak - 2018 Remaster", artista: "CHIC", year: 1978, spotifyId: "7Kszjzps0xbQXyo1pO4KfE" },
    { titulo: "Girl, You'll Be A Woman Soon", artista: "Neil Diamond", year: 1968, spotifyId: "1BmVQ5RGqqtF5cnsv6cQYu" },
    { titulo: "The Middle", artista: "Jimmy Eat World", year: 2001, spotifyId: "6GG73Jik4jUlQCkKg9JuGO" },
    { titulo: "Yo Quisiera", artista: "Reik", year: 2005, spotifyId: "2GSr8anleCXKLNjjjijoMZ" },
    { titulo: "Contigo Aprendí", artista: "Armando Manzanero", year: 1967, spotifyId: "7IcqJ3eMGs7pJ1BOCgPSFu" },
    { titulo: "Johnny B. Goode", artista: "Chuck Berry", year: 1959, spotifyId: "2QfiRTz5Yc8DdShCxG1tB2" },
    { titulo: "I Wanna Dance with Somebody (Who Loves Me)", artista: "Whitney Houston", year: 1987, spotifyId: "2tUBqZG2AbRi7Q0BIrVrEj" },
    { titulo: "Waterloo", artista: "ABBA", year: 1974, spotifyId: "3Dy4REq8O09IlgiwuHQ3sk" },
    { titulo: "Oh, Pretty Woman", artista: "Roy Orbison", year: 1962, spotifyId: "48i055G1OT5KxGGftwFxWy" },
    { titulo: "(We're Gonna) Rock Around The Clock", artista: "Bill Haley & His Comets", year: 1955, spotifyId: "1uRKT2LRANv4baowBWHfDS" },
    { titulo: "Tusa", artista: "KAROL G", year: 2019, spotifyId: "7k4t7uLgtOxPwTpFmtJNTY" },
    { titulo: "Rosa Pastel", artista: "Belanova", year: 2006, spotifyId: "3mU0DbuWtUX5KCaovOQZVK" },
    { titulo: "La Puerta de Alcalá", artista: "Ana Belén", year: 1979, spotifyId: "29opVIw8I1BOZntEn3Un2I" },
    { titulo: "I Love It (feat. Charli XCX)", artista: "Icona Pop", year: 2013, spotifyId: "2U8NXPTXZWG2O0ye2sYRiH" },
    { titulo: "Toxic", artista: "Britney Spears", year: 2003, spotifyId: "6I9VzXrHxO9rA9A5euc8Ak" },
    { titulo: "Funkytown", artista: "Lipps Inc.", year: 2018, spotifyId: "37yIrMPeJYRm7zJ8rr3Uvv" },
    { titulo: "Umbrella", artista: "Rihanna", year: 2007, spotifyId: "2yPoXCs7BSIUrucMdK5PzV" },
    { titulo: "El 7 de Septiembre", artista: "Mecano", year: 1991, spotifyId: "2fECkGQuw6xt5ObElhbiC1" },
    { titulo: "Amor Eterno", artista: "Rocío Dúrcal", year: 1984, spotifyId: "2TC4v9YiuQYk3Tk8RH7fV4" },
    { titulo: "Super Freak", artista: "Rick James", year: 1981, spotifyId: "2dCmGcEOQrMQhMMS8Vj7Ca" },
    { titulo: "Lamento Boliviano", artista: "Los Enanitos Verdes", year: 1994, spotifyId: "6Pur3hWy6Nzc27ilmsp5HA" },
    { titulo: "Another Day in Paradise - 2016 Remaster", artista: "Phil Collins", year: 1989, spotifyId: "1NCuYqMc8hKMb4cpNTcJbD" },
    { titulo: "Bésame Mucho", artista: "Emilio Tuero", year: 1997, spotifyId: "2vgVvWWd6Hsm9ixcttMzSx" },
    { titulo: "Flowers", artista: "Miley Cyrus", year: 2023, spotifyId: "0yLdNVWF3Srea0uzk55zFn" },
    { titulo: "MMMBop - Single Version", artista: "Hanson", year: 2006, spotifyId: "2HNZxbvFvasRtlOJ9M6DgR" },
    { titulo: "Stressed Out", artista: "Twenty One Pilots", year: 2015, spotifyId: "3CRDbSIZ4r5MsZ0YwxuEkn" },
    { titulo: "Súbete a Mi Moto", artista: "Menudo", year: 1998, spotifyId: "1CNUozOLzsqVQxrct155hY" },
    { titulo: "Hotel California - 2013 Remaster", artista: "Eagles", year: 1976, spotifyId: "40riOy7x9W7GXjyGp4pjAv" },
    { titulo: "Dynamite", artista: "BTS", year: 2020, spotifyId: "5QDLhrAOJJdNAmCTJ8xMyW" },
    { titulo: "Uptown Funk (feat. Bruno Mars)", artista: "Mark Ronson", year: 2015, spotifyId: "32OlwWuMpZ6b0aN2RZOeMS" },
    { titulo: "Escápate Conmigo (feat. Ozuna)", artista: "Wisin", year: 2017, spotifyId: "1KSqYYJFyfTecXFk9M0prc" },
    { titulo: "La Bamba - Single Version", artista: "Ritchie Valens", year: 1959, spotifyId: "2aEeghgUcnu75tzcolFMfs" },
    { titulo: "MIA", artista: "Bad Bunny", year: 2018, spotifyId: "3gE4eQH3K83Sght0ZLvuBK" },
    { titulo: "El Amante", artista: "Nicky Jam", year: 2017, spotifyId: "3umS4y3uQDkqekNjVpiRUs" },
    { titulo: "Mi Persona Favorita", artista: "Río Roma", year: 2014, spotifyId: "70fVcEP5pRrxaIICY3DcPe" },
    { titulo: "Replay", artista: "Iyaz", year: 2009, spotifyId: "5vlEg2fT4cFWAqU5QptIpQ" },
    { titulo: "What Is Love - 7\" Mix", artista: "Haddaway", year: 1993, spotifyId: "2IHaGyfxNoFPLJnaEg4GTs" },
    { titulo: "The Hustle - Original Mix", artista: "Van McCoy", year: 1975, spotifyId: "6hYT9vkr0xMjhBlaLsYq9T" },
    { titulo: "Ojos Marrones", artista: "Lasso", year: 2022, spotifyId: "7gwT3HGL84vF7bgtwL1N88" },
    { titulo: "Parchis - La cancion de…", artista: "Parchis", year: 2005, spotifyId: "5UiQoY4aSp3cY9V7t6k0S1" },
    { titulo: "Maneater", artista: "Daryl Hall & John Oates", year: 1982, spotifyId: "7j74lucZ59vqN67Ipe2ZcY" },
    { titulo: "Bye Bye Bye", artista: "*NSYNC", year: 2000, spotifyId: "62bOmKYxYg7dhrC6gH9vFn" },
    { titulo: "The Lazy Song", artista: "Bruno Mars", year: 2010, spotifyId: "386RUes7n1uM1yfzgeUuwp" },
    { titulo: "Strangers In The Night", artista: "Frank Sinatra", year: 1966, spotifyId: "74VR3AkGPhbYXnxcOYa16x" },
    { titulo: "Break My Heart", artista: "Dua Lipa", year: 2020, spotifyId: "017PF4Q3l4DBUiWoXk4OWT" },
    { titulo: "Marimar", artista: "Thalia", year: 1994, spotifyId: "6NjpVc4lf4yIVns9d0WPNb" },
    { titulo: "Todos Me Miran", artista: "Gloria Trevi", year: 2006, spotifyId: "4pmRDyDRRiZ5Pq7hm4WTpb" },
    { titulo: "Payasito (Ponchinello)", artista: "Enrique Guzman", year: 1991, spotifyId: "0bfNMCcujmZHi03rkpFmAL" },
    { titulo: "La Incondicional", artista: "Luis Miguel", year: 1988, spotifyId: "6F9yAYUaNbUhdlQyt5uZ3b" },
    { titulo: "En el 2000", artista: "Natalia Lafourcade", year: 2002, spotifyId: "2cVJwPD5CaTx2kBZyomzGN" },
    { titulo: "Darte un Beso", artista: "Prince Royce", year: 2013, spotifyId: "6cJLfIqwh0tCKRjYM3WpZ5" },
    { titulo: "La Plaga (Good Golly, Miss Molly)", artista: "Los Teen Tops", year: 1960, spotifyId: "6U4PNy60GmjVdmdMxZxtjB" },
    { titulo: "Yo no te pido la luna (Non voglio mica la luna)", artista: "Daniela Romo", year: 1984, spotifyId: "09uE7kHv2ESkvtInKugpGM" },
    { titulo: "Dame Felicidad (Free Me)", artista: "Enrique Guzman", year: 1991, spotifyId: "23phbG3PUXEDUFq0ndNgGq" },
    { titulo: "Estare", artista: "Kabah", year: 1996, spotifyId: "7H4kdYuy4xwDurVT5zvVuM" },
    { titulo: "Maldita Primavera", artista: "Yuri", year: 2007, spotifyId: "3GUyiFEglEm9rSToOf5YZW" },
    { titulo: "As It Was", artista: "Harry Styles", year: 2022, spotifyId: "4LRPiXqCikLlN15c3yImP7" },
    { titulo: "Pepas", artista: "Farruko", year: 2021, spotifyId: "5fwSHlTEWpluwOM0Sxnh5k" },
    { titulo: "Lo Que No Fue No Será", artista: "José José", year: 1980, spotifyId: "3nlBG0lCutyuRX3jDRALw0" },
    { titulo: "Hit the Road Jack", artista: "Ray Charles", year: 2012, spotifyId: "49fzPkBb3aOUWYRKaTWVhm" },
    { titulo: "Miedo", artista: "Pepe Aguilar", year: 2004, spotifyId: "1ZAkJE2vi1wbo7tyvgWuXN" },
    { titulo: "In the Mood", artista: "Glenn Miller", year: 1996, spotifyId: "6dZKWYSx5YBIme4SfpIHJ0" },
    { titulo: "Bella", artista: "Mijares", year: 2004, spotifyId: "4ZIxw3u6TeexXd8rK9DqhL" },
    { titulo: "Agujetas de Color de Rosa (Pink Shoe Laces)", artista: "Los Hooligans", year: 2007, spotifyId: "4ub7vWkgBWI7fv5DiKPMiA" },
    { titulo: "Hacer El Amor Con Otro", artista: "Alejandra Guzman", year: 1991, spotifyId: "1OB7cLxxCWA8gbbfjFNNej" },
    { titulo: "Besos En Guerra", artista: "Morat", year: 2018, spotifyId: "1mlGScrDQqHqmhdIqE8MmA" },
    { titulo: "Yo soy aquél", artista: "Raphael", year: 1967, spotifyId: "4H71d1kJ8DB8J4atO8fbBl" },
    { titulo: "Summer", artista: "Calvin Harris", year: 2014, spotifyId: "6YUTL4dYpB9xZO5qExPf05" },
    { titulo: "Viva La Vida", artista: "Coldplay", year: 2008, spotifyId: "3Fcfwhm8oRrBvBZ8KGhtea" },
    { titulo: "Born To Be Wild", artista: "Steppenwolf", year: 1968, spotifyId: "63OFKbMaZSDZ4wtesuuq6f" },
    { titulo: "This Love", artista: "Maroon 5", year: 2002, spotifyId: "6ECp64rv50XVz93WvxXMGF" },
    { titulo: "That Don't Impress Me Much", artista: "Shania Twain", year: 1999, spotifyId: "4I7DV3MIgxJGlObiy9s6nx" },
    { titulo: "1979", artista: "The Smashing Pumpkins", year: 2001, spotifyId: "3h5zik31hTTat9jmpCZZNC" },
    { titulo: "Despacito", artista: "Luis Fonsi", year: 2019, spotifyId: "6habFhsOp2NvshLv26DqMb" },
    { titulo: "Y.M.C.A.", artista: "Village People", year: 1978, spotifyId: "4YOJFyjqh8eAcbKFfv88mV" },
    { titulo: "En La Intimidad", artista: "Thalia", year: 1991, spotifyId: "5aqKCPNWmlbrZJCEjdSRPy" },
    { titulo: "Sweet Caroline", artista: "Neil Diamond", year: 1969, spotifyId: "62AuGbAkt8Ox2IrFFb8GKV" },
    { titulo: "Crazy", artista: "Gnarls Barkley", year: 2006, spotifyId: "2N5zMZX7YeL1tico8oQxa9" },
    { titulo: "Iris", artista: "The Goo Goo Dolls", year: 1998, spotifyId: "6Qyc6fS4DsZjB2mRW9DsQs" },
    { titulo: "Que Lloro", artista: "Sin Bandera", year: 2003, spotifyId: "62clthR0fZmLbxeqxVJatQ" },
    { titulo: "Karma Chameleon - Remastered 2002", artista: "Culture Club", year: 2022, spotifyId: "5muHy7Z0bHM4uqExt081ue" },
    { titulo: "Like a Virgin", artista: "Madonna", year: 1984, spotifyId: "1ZPlNanZsJSPK5h9YZZFbZ" },
    { titulo: "Amorcito corazón", artista: "Pedro Infante", year: 1998, spotifyId: "73WX2V6JVfyQYYIG3K76i8" },
    { titulo: "How You Remind Me", artista: "Nickelback", year: 2001, spotifyId: "0gmbgwZ8iqyMPmXefof8Yf" },
    { titulo: "Cómo Te Va Mi Amor", artista: "Pandora", year: 1990, spotifyId: "6Vy53iriyX8Vqx0V68Jzn2" },
    { titulo: "Crazy", artista: "Aerosmith", year: 1993, spotifyId: "3QxKpdTB8ZSFn8MGeCCpsQ" },
    { titulo: "Hello", artista: "Adele", year: 2015, spotifyId: "1Yk0cQdMLx5RzzFTYwmuld" },
    { titulo: "Thunder", artista: "Imagine Dragons", year: 2017, spotifyId: "1zB4vmk8tFRmM9UULNzbLB" },
    { titulo: "Bésame mucho", artista: "Los Panchos", year: 2018, spotifyId: "7m5p9YuuC8Z9XwS1kYrZFH" },
    { titulo: "Rosas", artista: "La Oreja de Van Gogh", year: 2003, spotifyId: "4waqcUQWdj0yH26STWl2Rq" },
    { titulo: "Cómo Te Voy A Olvidar", artista: "Los Ángeles Azules", year: 1996, spotifyId: "51dNexiESqcJLsGLrmg1Nv" },
    { titulo: "Take Me Home, Country Roads - Original Version", artista: "John Denver", year: 1971, spotifyId: "1YYhDizHx7PnDhAhko6cDS" },
    { titulo: "Estoy Pensando en Ti", artista: "La Sonora Santanera", year: 1968, spotifyId: "1X2VZSug0EnkzDqVSin47F" },
    { titulo: "Sugar", artista: "Maroon 5", year: 2014, spotifyId: "2iuZJX9X9P0GKaE93xcPjk" },
    { titulo: "Everybody Hurts", artista: "R.E.M.", year: 1992, spotifyId: "6PypGyiu0Y2lCDBN1XZEnP" },
    { titulo: "Soy Yo", artista: "Bomba Estéreo", year: 2015, spotifyId: "4Egb5xP6cniUx0kgZd5zLB" },
    { titulo: "La Interesada", artista: "Chava Flores", year: 2004, spotifyId: "5UbjsmHa2M69q2Q1bzmDBE" },
    { titulo: "Get Lucky (feat. Pharrell Williams and Nile Rodgers)", artista: "Daft Punk", year: 2013, spotifyId: "69kOkLUCkxIZYexIgSG8rq" },
    { titulo: "El Reloj", artista: "Los Tres Caballeros", year: 1994, spotifyId: "27u17peWruKyUe7RfBglZC" },
    { titulo: "Cien años", artista: "Pedro Infante", year: 1998, spotifyId: "760r2LXNtMaHDKMQ5wkXbi" },
    { titulo: "Silly Love Songs", artista: "Wings", year: 2001, spotifyId: "5Qhfo6ZqoA2oPF5uFf43L3" },
    { titulo: "November Rain", artista: "Guns N' Roses", year: 1991, spotifyId: "3YRCqOhFifThpSRFJ1VWFM" },
    { titulo: "Disco Inferno", artista: "The Trammps", year: 1976, spotifyId: "5jUA1njy3h6ynHLvPdEVHt" },
    { titulo: "My Heart Will Go On - Love Theme from \"Titanic\"", artista: "Céline Dion", year: 1997, spotifyId: "33LC84JgLvK2KuW43MfaNq" },
    { titulo: "Heart Of Glass", artista: "Blondie", year: 2006, spotifyId: "41AE8ODX2JETBCa6muhSLY" },
    { titulo: "Señorita", artista: "Shawn Mendes", year: 2019, spotifyId: "0TK2YIli7K1leLovkQiNik" },
    { titulo: "bad guy", artista: "Billie Eilish", year: 2019, spotifyId: "2Fxmhks0bxGSBdJ92vM42m" },
    { titulo: "Blinding Lights", artista: "The Weeknd", year: 2020, spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
    { titulo: "Vogue", artista: "Madonna", year: 1990, spotifyId: "7j5TIXPi0cCbSSqItmbyZy" },
    { titulo: "Zombie", artista: "The Cranberries", year: 1994, spotifyId: "7EZC6E7UjZe63f1jRmkWxt" },
    { titulo: "Let Her Cry", artista: "Hootie & The Blowfish", year: 1994, spotifyId: "6NGi23FFKq9tH5NR1NcTw2" },
    { titulo: "Flashdance...What a Feeling - Radio Edit", artista: "Irene Cara", year: 1983, spotifyId: "3cbV252akVZInSvJk7jAYX" },
    { titulo: "Don't Turn Around", artista: "Ace of Base", year: 1993, spotifyId: "4SYMibQ93bfzOk6uzkF0dO" },
    { titulo: "Muriendo Lento", artista: "Timbiriche", year: 1993, spotifyId: "1qqk4LVn8q3kJBjDcXkTGh" },
    { titulo: "La Chica de Humo", artista: "Emmanuel", year: 1989, spotifyId: "0GZ8UVlhn2tjHPpngzoLJk" },
    { titulo: "Sexo Pudor Y Lágrimas", artista: "Aleks Syntek", year: 1999, spotifyId: "27qjcww3SKGeD4wTUOJEeh" },
    { titulo: "Scars To Your Beautiful", artista: "Alessia Cara", year: 2016, spotifyId: "42ydLwx4i5V49RXHOozJZq" },
    { titulo: "Need You Tonight", artista: "INXS", year: 1987, spotifyId: "5eU8qMd0TpaLqTGDZJaLDs" },
    { titulo: "No Role Modelz", artista: "J. Cole", year: 2014, spotifyId: "68Dni7IE4VyPkTOH9mRWHr" },
    { titulo: "Get Back - Remastered 2009", artista: "The Beatles", year: 1970, spotifyId: "4MLBqAEzNN89o2M9h92Z26" },
    { titulo: "Mona Lisa", artista: "Nat King Cole", year: 1954, spotifyId: "5dae01pKNjRQtgOeAkFzPY" },
    { titulo: "Wonderwall", artista: "Oasis", year: 1995, spotifyId: "1qPbGZqppFwLwcBC1JQ6Vr" },
    { titulo: "I Shot The Sheriff", artista: "Eric Clapton", year: 1974, spotifyId: "0UOxp1BpnD8uPQMKU4wKjz" },
    { titulo: "Mambo No. 8", artista: "Pérez Prado", year: 1999, spotifyId: "7gvrntH4fFWZWKwpPLWjgw" },
    { titulo: "Mon amour", artista: "zzoilo", year: 2020, spotifyId: "064ikblBFGS6HL35D71LZy" },
    { titulo: "Wrecking Ball", artista: "Miley Cyrus", year: 2013, spotifyId: "2vwlzO0Qp8kfEtzTsCXfyE" },
    { titulo: "Don't Stop Believin'", artista: "Journey", year: 1981, spotifyId: "4bHsxqR3GMrXTxEPLuK5ue" },
    { titulo: "Since U Been Gone", artista: "Kelly Clarkson", year: 2004, spotifyId: "3xrn9i8zhNZsTtcoWgQEAd" },
    { titulo: "Los Malaventurados No Lloran", artista: "PXNDX", year: 2006, spotifyId: "66PRDvzBHhbcdbc4T4mrZY" },
    { titulo: "All That She Wants", artista: "Ace of Base", year: 1993, spotifyId: "6kWJvPfC4DgUpRsXKNa9z9" },
    { titulo: "Mi soledad y yo", artista: "Alejandro Sanz", year: 1995, spotifyId: "3GFLbBgMuY2RELNo6tMqOS" },
    { titulo: "Surfin' U.S.A. (Mono)", artista: "The Beach Boys", year: 1963, spotifyId: "2dbaIpJoAk2hhrrX2ljKJo" },
    { titulo: "A quien tú decidiste amar", artista: "Sandoval", year: 2009, spotifyId: "3lJwIAfeWtnNRbJXWbIHKD" },
    { titulo: "Love Me Like You Do - From \"Fifty Shades Of Grey\"", artista: "Ellie Goulding", year: 2015, spotifyId: "3zHq9ouUJQFQRf3cm1rRLu" },
    { titulo: "Mr. Jones", artista: "Counting Crows", year: 1993, spotifyId: "5DiXcVovI0FcY2s0icWWUu" },
    { titulo: "Sk8er Boi", artista: "Avril Lavigne", year: 2002, spotifyId: "00Mb3DuaIH1kjrwOku9CGU" },
    { titulo: "Un Alma en Pena", artista: "Lucía Méndez", year: 2011, spotifyId: "19a0LWL0uI0ggevU7QpzpG" },
    { titulo: "Baby", artista: "Justin Bieber", year: 2010, spotifyId: "6epn3r7S14KUqlReYr77hA" },
    { titulo: "Devuélveme a mi chica", artista: "Hombres G", year: 1985, spotifyId: "1Wrzhfa5bNlqvsnCztz190" },
    { titulo: "Ice Ice Baby", artista: "Vanilla Ice", year: 1990, spotifyId: "11d9oUiwHuYt216EFA2tiz" },
    { titulo: "STAY (with Justin Bieber)", artista: "The Kid LAROI", year: 2021, spotifyId: "5HCyWlXZPP0y6Gqq8TgA20" },
    { titulo: "SexyBack (feat. Timbaland)", artista: "Justin Timberlake", year: 2006, spotifyId: "0O45fw2L5vsWpdsOdXwNAR" },
    { titulo: "Donde Estas Corazon", artista: "Shakira", year: 1995, spotifyId: "6IGvaQ4aFBjy66TdUurIiA" },
    { titulo: "Adiós Amor", artista: "Christian Nodal", year: 2017, spotifyId: "63bmZnBN1CiJ9sA4qTEe8y" },
    { titulo: "Sugar, Sugar", artista: "The Archies", year: 2007, spotifyId: "3iSws76HjaU7k49EqJVTfF" },
    { titulo: "INDUSTRY BABY (feat. Jack Harlow)", artista: "Lil Nas X", year: 2021, spotifyId: "27NovPIUIRrOZoCHxABJwK" },
    { titulo: "The Locomotion", artista: "Little Eva", year: 1962, spotifyId: "5xzdDMhFYiuUONB0Mha9VS" },
    { titulo: "María Bonita", artista: "Agustín Lara", year: 2001, spotifyId: "6eD6RGKhnI6AZhGPRXMGGd" },
    { titulo: "La Bikina", artista: "Juan Torres", year: 1991, spotifyId: "1CTWQpPUhy1hlqd1GGzO3O" },
    { titulo: "Kilómetros", artista: "Sin Bandera", year: 2003, spotifyId: "1AfAFpHJ7s4unBIhe3NM5j" },
    { titulo: "Somebody That I Used to Know", artista: "Gotye", year: 2011, spotifyId: "62oaDoBveZxvZb94ziiMXi" },
    { titulo: "Favorito", artista: "Camilo", year: 2020, spotifyId: "0Snbzbd74RLfL0i4nn1vU5" },
    { titulo: "Take on Me", artista: "a-ha", year: 1985, spotifyId: "2WfaOiMkCvy7F5fcp2zZ8L" },
    { titulo: "Desesperada", artista: "Marta Sánchez", year: 1993, spotifyId: "20WaSPMyeIO7NntPpn1FM5" },
    { titulo: "Anti-Hero", artista: "Taylor Swift", year: 2022, spotifyId: "0V3wPSX9ygBnCm8psDIegu" },
];