const CANCIONES = [
    { title: "Blitzkrieg Bop", artist: "Ramones", year: 1976, spotifyId: "4KcH1ZRV2W1q7Flq0QqC76" },
    { title: "En algún lugar", artist: "Duncan Dhu", year: 1987, spotifyId: "3UIENhLRdFIOuRan92cAQu" },
    { title: "One More Time", artist: "Daft Punk", year: 2000, spotifyId: "2Uy6EhQXAYkXA6MohPgjpV" },
    { title: "México Lindo y Querido", artist: "Jorge Negrete", year: 1950, spotifyId: "567aGQVtUEhNuDpp9Dtewp" },
    { title: "Tequila", artist: "The Champs", year: 1958, spotifyId: "5gJKsGij5oGt5H5RSFYXPa" },
    { title: "Regalo de Dios", artist: "Julión Alvares y su Norteño Banda", year: 2023, spotifyId: "51qYdMBxt9mFbtZBzq1Yfi" },
    { title: "Oblivion", artist: "Grimes", year: 2012, spotifyId: "4BY4V1T0RJK1HmD2Q0ClyK" },
    { title: "Piano Man", artist: "Billy Joel", year: 1973, spotifyId: "78WVLOP9pN0G3gRLFy1rAa" },
    { title: "We Own the Night", artist: "Dance Gavin Dance", year: 2015, spotifyId: "7xCcUcMcGsIYGKUVgBZUw5" },
    { title: "Contrabando y Traición", artist: "Los Tigres del Norte", year: 1974, spotifyId: "4gRi0itWso2UodoRMP5asJ" },
    { title: "Manic Monday", artist: "The Bangles", year: 1985, spotifyId: "798fUF6UnRn27xiVuKyJCi" },
    { title: "Callaita", artist: "Bad Bunny", year: 2019, spotifyId: "2TH65lNHgvLxCKXM3apjxI" },
    { title: "Nube Viajera", artist: "Alejandro Fernández", year: 1996, spotifyId: "7qOjjzbvSsdHcAU31va4rz" },
    { title: "I Will Wait", artist: "Mumford & Sons", year: 2012, spotifyId: "0hm8rgOY17z7kQJlqGKbu7" },
    { title: "Vuela, Vuela", artist: "Magneto", year: 2007, spotifyId: "6nz1ojKuYx5HO7Vh0wmuWp" },
    { title: "Te Sigo Amando", artist: "Juan Gabriel", year: 1980, spotifyId: "3Bn5su26JosHjkbIrxgz0j" },
    { title: "Someone You Loved", artist: "Lewis Capaldi", year: 2018, spotifyId: "2TIlqbIneP0ZY1O0EzYLlc" },
    { title: "Autos, Moda Y Rock N Roll", artist: "Fandango", year: 1987, spotifyId: "5JiRlyOGE2EYvzLyex6pdK" },
    { title: "Bazar", artist: "Flans", year: 1985, spotifyId: "7CLxH03q65I3aktL79k4vE" },
    { title: "Africa", artist: "TOTO", year: 1982, spotifyId: "2374M0fQpWi3dLnB54qaLX" },
    { title: "Jamás", artist: "Camilo Sesto", year: 1975, spotifyId: "0ScrUVrcTYIZijbqDZ3CJE" },
    { title: "Ginza", artist: "J Balvin", year: 2016, spotifyId: "2C2TGgFzrTRIOdQS1vUN5h" },
    { title: "Cielito Lindo", artist: "Quirino Mendoza", year: 1943, spotifyId: "4nCbfSswiUfK7feYrx7baB" },
    { title: "Quevedo: Bzrp Music Sessions, Vol. 52/66", artist: "Bizarrap", year: 2022, spotifyId: "2tTmW7RDtMQtBk7m2rYeSw" },
    { title: "Al Final", artist: "Emmanuel", year: 1988, spotifyId: "3yeT1oIBRGuEhOb3OCvL2z" },
    { title: "La Mordidita", artist: "Ricky Martin (feat. Yotuel)", year: 2015, spotifyId: "00i0O74dXdaKKdCrqHnfXm" },
    { title: "Beat It", artist: "Michael Jackson", year: 1982, spotifyId: "1OOtq8tRnDM8kG2gqUPjAj" },
    { title: "Siempre Tuya Desde La Raíz", artist: "Paulina Rubio", year: 1996, spotifyId: "7yXXFYlLaA2cjcbnij7e5h" },
    { title: "Firework", artist: "Katy Perry", year: 2010, spotifyId: "1mXuMM6zjPgjL4asbBsgnt" },
    { title: "Vivir Mi Vida", artist: "Marc Anthony", year: 2013, spotifyId: "3QHMxEOAGD51PDlbFPHLyJ" },
    { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987, spotifyId: "7o2CTH4ctstm8TNelqjb51" },
    { title: "Oops!...I Did It Again", artist: "Britney Spears", year: 2000, spotifyId: "6naxalmIoLFWR0siv8dnQQ" },
    { title: "Ni Lo Intentes", artist: "Julión Álvarez y su Norteño Banda", year: 2010, spotifyId: "3WiU6ZeOD7UFjTSPraQMPl" },
    { title: "Mi Pueblo", artist: "Cesar Costa", year: 2008, spotifyId: "3SSOvO40lo6wmz8r0Kt3M1" },
    { title: "Walk This Way", artist: "Aerosmith", year: 1975, spotifyId: "5SZ6zX4rOrEQferfFC2MfP" },
    { title: "It's My Life", artist: "Bon Jovi", year: 2000, spotifyId: "6iNBM60VQtPUUhkKfwa5KV" },
    { title: "Mientes", artist: "Camila", year: 2010, spotifyId: "5EhzE6HJaCcLFrf5rPqvpk" },
    { title: "Tú Y Yo Somos Uno Mismo", artist: "Timbiriche", year: 1988, spotifyId: "1K7bwHdwsTjt9YiNmiib0P" },
    { title: "Mío", artist: "Paulina Rubio", year: 1992, spotifyId: "77GJz1FIKgjIp9KtnGc8Fl" },
    { title: "Todo Cambió", artist: "Camila", year: 2006, spotifyId: "4OyzSXRSadNQt5EMwASdap" },
    { title: "Smoke Gets In Your Eyes", artist: "The Platters", year: 1958, spotifyId: "57yz5oqMytzbwdewSG28L9" },
    { title: "You Sexy Thing", artist: "Hot Chocolate", year: 1975, spotifyId: "3jAG0kb7gg0vGeFFZj6bBt" },
    { title: "Let It Be", artist: "The Beatles", year: 1970, spotifyId: "7iN1s7xHE4ifF5povM6A48" },
    { title: "You Get What You Give", artist: "New Radicals", year: 1998, spotifyId: "1Cwsd5xI8CajJz795oy4XF" },
    { title: "(I've Had) The Time of My Life", artist: "Bill Medley", year: 1987, spotifyId: "1UvTPXlImVd4jcucK4qJwb" },
    { title: "Amiga mía", artist: "Alejandro Sanz", year: 1997, spotifyId: "6kQYMqjobmB8MkWwa9OUyA" },
    { title: "Querida", artist: "Juan Gabriel", year: 1984, spotifyId: "5ySxlyvySBhIEvoO2xx7uT" },
    { title: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987, spotifyId: "4cOdK2wGLETKBW3PvgPWqT" },
    { title: "Felices los 4", artist: "Maluma", year: 2018, spotifyId: "1RouRzlg8OKFeqc6LvdxmB" },
    { title: "Twist And Shout", artist: "The Isley Brothers", year: 1961, spotifyId: "7iFdUmdqT9XrsJdSGf9KrX" },
    { title: "No One", artist: "Alicia Keys", year: 2007, spotifyId: "6IwKcFdiRQZOWeYNhUiWIv" },
    { title: "La Media Vuelta", artist: "José Alfredo Jimenez", year: 1962, spotifyId: "0QvxVQaOUIMgqxyvk9GpFE" },
    { title: "No Podras", artist: "Cristian Castro", year: 1992, spotifyId: "6ZIwZmQ2ph6QK13sItmDEx" },
    { title: "Shake It Off", artist: "Taylor Swift", year: 2014, spotifyId: "5xTtaWoae3wi06K5WfVUUH" },
    { title: "Amigo", artist: "Roberto Carlos", year: 2003, spotifyId: "24Thqkee9KZgifP7G8c70N" },
    { title: "Te Vi", artist: "Piso 21", year: 2018, spotifyId: "059bcIhyc2SBwm6sw2AZzd" },
    { title: "Hollaback Girl", artist: "Gwen Stefani", year: 2004, spotifyId: "0LzrhCZFXW94Y8nwtTuRlw" },
    { title: "Volver, Volver", artist: "Vicente Fernández", year: 1972, spotifyId: "4Fvnz1ZJ86IdqDAepWYPAh" },
    { title: "Andar Conmigo", artist: "Julieta Venegas", year: 2003, spotifyId: "05iMQqncVBIm4AE26EvaTL" },
    { title: "American Pie", artist: "Don McLean", year: 1971, spotifyId: "1fDsrQ23eTAVFElUMaf38X" },
    { title: "Ni tú ni nadie", artist: "Alaska Y Dinarama", year: 1984, spotifyId: "7LpS82vPDLgZAHWRtWBBRj" },
    { title: "El Final", artist: "Rostros Ocultos", year: 2017, spotifyId: "39ELDQVDsgBmo5gbTuru9U" },
    { title: "Blurred Lines", artist: "Robin Thicke", year: 2013, spotifyId: "2pgbGOb00WrlXY3ZRFKn7v" },
    { title: "I Like You (A Happier Song)", artist: "Post Malone (with Doja Cat)", year: 2022, spotifyId: "0O6u0VJ46W86TxN9wgyqDj" },
    { title: "All I Wanna Do Is Make Love To You", artist: "Heart", year: 1990, spotifyId: "5YjKdeES9QRJ8NmF4Xc8pV" },
    { title: "La Pachanga", artist: "Vilma Palma e Vampiros", year: 1991, spotifyId: "1x6bkwDyWIOZNFY5blRSs1" },
    { title: "Thinking out Loud", artist: "Ed Sheeran", year: 2014, spotifyId: "34gCuhDGsG4bRPIf9bb02f" },
    { title: "Poker Face", artist: "Lady Gaga", year: 2008, spotifyId: "5R8dQOPq8haW94K7mgERlO" },
    { title: "Fireflies", artist: "Owl City", year: 2009, spotifyId: "3DamFFqW32WihKkTVlwTYQ" },
    { title: "Jump", artist: "Van Halen", year: 1984, spotifyId: "6Fba9RZtC6vTY814JToDtP" },
    { title: "Eternamente Bella", artist: "Alejandra Guzman", year: 1990, spotifyId: "3pIgumKqXX7ge7lT9rCvNy" },
    { title: "You're Beautiful", artist: "James Blunt", year: 2005, spotifyId: "0vg4WnUWvze6pBOJDTq99k" },
    { title: "I Gotta Feeling", artist: "Black Eyed Peas", year: 2009, spotifyId: "2H1047e0oMSj10dgp7p2VG" },
    { title: "La Muralla Verde", artist: "Los Enanitos Verdes", year: 1986, spotifyId: "6OKhBvddAlWxxFnjbpilhu" },
    { title: "Say So", artist: "Doja Cat", year: 2019, spotifyId: "3Dv1eDb0MEgF93GpLXlucZ" },
    { title: "Ironic", artist: "Alanis Morissette", year: 1995, spotifyId: "1d6KS9GH06JAd19uiBy9IE" },
    { title: "With Or Without You", artist: "U2", year: 1987, spotifyId: "1Og8U5KRel9D51h4bmznlE" },
    { title: "I Like To Move It - Erick \"More\" Album Mix", artist: "Reel 2 Real (feat. The Mad Stuntman)", year: 1994, spotifyId: "6dHTkQYY3zdR9i9Nj0IGVW" },
    { title: "Heaven", artist: "Bryan Adams", year: 1984, spotifyId: "7Ewz6bJ97vUqk5HdkvguFQ" },
    { title: "Soak Up The Sun", artist: "Sheryl Crow", year: 2002, spotifyId: "215JYyyUnrJ98NK3KEwu6d" },
    { title: "Rayando el Sol", artist: "Maná", year: 1990, spotifyId: "4Ofg5uuH7qqDIXpAJMpXZV" },
    { title: "It Wasn't Me", artist: "Shaggy", year: 2000, spotifyId: "3WkibOpDF7cQ5xntM1epyf" },
    { title: "Usted", artist: "Los Tres Diamantes", year: 1971, spotifyId: "1Wt3vmlSvvdyjeizfXsyrg" },
    { title: "Start Me Up", artist: "The Rolling Stones", year: 1981, spotifyId: "7HKez549fwJQDzx3zLjHKC" },
    { title: "Runaway Train", artist: "Soul Asylum", year: 1993, spotifyId: "3Ib3SJV8ZXuLvDiDb2w1As" },
    { title: "Verónica", artist: "Victor Yturbe", year: 1977, spotifyId: "0TwbY0aX7jIgJLFXZCUcti" },
    { title: "¿Cómo Pagarte?", artist: "Carlos Rivera", year: 2016, spotifyId: "7kkJnzW5TlGwzYYcps0Qv9" },
    { title: "Lo Dudo", artist: "José José", year: 1985, spotifyId: "65vU70CBDU0sQDfOWkwUEH" },
    { title: "Si No Te Hubieras Ido", artist: "Marco Antonio Solís", year: 2011, spotifyId: "3l1ZanpJ3jFQZMqATizqfE" },
    { title: "Provócame", artist: "Chayanne", year: 1992, spotifyId: "3mbQd1v6N7nqX2mcAyCxCU" },
    { title: "Persiana Americana", artist: "Soda Stereo", year: 1986, spotifyId: "71awpJoi5bqGMBrTkHDDoL" },
    { title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: 1983, spotifyId: "4y1LsJpmMti1PfRQV9AWWe" },
    { title: "Crazy In Love", artist: "Beyoncé (feat. JAY-Z)", year: 2003, spotifyId: "5IVuqXILoxVWvWEPm82Jxr" },
    { title: "Thunderstruck", artist: "AC/DC", year: 1990, spotifyId: "57bgtoPSgt236HzfBOd8kj", aliases: {"artist":["ACDC"]} },
    { title: "I Got You Babe", artist: "Sonny & Cher", year: 1965, spotifyId: "4SGBuq37Ol4HJr7pQqFMKa" },
    { title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", year: 1974, spotifyId: "7e89621JPkKaeDSTQ3avtg" },
    { title: "drivers license", artist: "Olivia Rodrigo", year: 2021, spotifyId: "5wANPM4fQCJwkGd4rN57mH" },
    { title: "Cruz de navajas", artist: "Mecano", year: 1986, spotifyId: "6VWWU8EFSS7Xx1TZ830Paz" },
    { title: "I Will Always Love You", artist: "Whitney Houston", year: 1992, spotifyId: "4eHbdreAnSOrDDsFfc4Fpm" },
    { title: "Right Here Waiting", artist: "Richard Marx", year: 1989, spotifyId: "4LFwNJWoj74Yd71fIr1W8x" },
    { title: "December, 1963 (Oh What a Night!)", artist: "Frankie Valli &The Four Seasons", year: 1975, spotifyId: "1hQFF33xi8ruavZNyovtUN" },
    { title: "Hey Ya!", artist: "Outkast", year: 2003, spotifyId: "2PpruBYCo4H7WOBJ7Q2EwM" },
    { title: "Sweet Dreams (Are Made of This)", artist: "Eurythmics", year: 1983, spotifyId: "6oWLiyRpo1ibp2vKNxHG0T" },
    { title: "Yeah!", artist: "USHER (feat. Lil Jon & Ludacris)", year: 2004, spotifyId: "5rb9QrpfcKFHM1EUbSIurX" },
    { title: "Tacones Rojos", artist: "Sebastian Yatra", year: 2021, spotifyId: "0Be7sopyKMv8Y8npsUkax2" },
    { title: "Si Nos Dejan", artist: "José Alfredo Jimenez", year: 1967, spotifyId: "1mTWvb5uY8R6tU7iCLtiUo" },
    { title: "That's Amore", artist: "Dean Martin", year: 1953, spotifyId: "6GYqOflskcZxPj8rkTZkOy" },
    { title: "Mírame a los Ojos", artist: "Onda Vaselina", year: 1997, spotifyId: "0q3P0vjpqqswJSukITnfZA" },
    { title: "Entre dos tierras", artist: "Heroes Del Silencio", year: 1990, spotifyId: "4rJdaSwOCHLBhxdMsymeMw" },
    { title: "I Want It That Way", artist: "Backstreet Boys", year: 1999, spotifyId: "47BBI51FKFwOMlIiX6m8ya" },
    { title: "Somos Novios", artist: "Armando Manzanero", year: 1990, spotifyId: "05CfvXFk8iDBJpxYHi8Kpq" },
    { title: "The Look", artist: "Roxette", year: 1988, spotifyId: "2oWMI54r0qT4N8Xb4C76vq" },
    { title: "Counting Stars", artist: "OneRepublic", year: 2013, spotifyId: "2tpWsVSb9UEmDRxAl1zhX1" },
    { title: "Barbie Girl", artist: "Aqua", year: 1997, spotifyId: "5ZrDlcxIDZyjOzHdYW1ydr" },
    { title: "Give A Little Bit", artist: "Supertramp", year: 1977, spotifyId: "6XUHsYE38CEbYunT983O9G" },
    { title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991, spotifyId: "4CeeEOM32jQcH3eN9Q2dGj" },
    { title: "Bule Bule", artist: "Los Rockin' Devils", year: 2004, spotifyId: "19Ol3nKQvIJJiKBTIOBzwi" },
    { title: "Escape (The Pina Colada Song)", artist: "Rupert Holmes", year: 1979, spotifyId: "5IMtdHjJ1OtkxbGe4zfUxQ" },
    { title: "Dance Monkey", artist: "Tones And I", year: 2019, spotifyId: "5ZULALImTm80tzUbYQYM9d" },
    { title: "I Got You (I Feel Good)", artist: "James Brown", year: 1965, spotifyId: "5haXbSJqjjM0TCJ5XkfEaC" },
    { title: "Ya Me Enteré", artist: "Reik", year: 2016, spotifyId: "0lPXFrKyl8HkdQ2E6NmNja" },
    { title: "No Volvere", artist: "Miguel Aceves Mejia", year: 2001, spotifyId: "31FSxMxEOyc9kzz3Mdmvlz" },
    { title: "Solamente una Vez", artist: "Agustín Lara", year: 1941, spotifyId: "3KXT4z3ZtA8yasFoqltxzP" },
    { title: "Hips Don't Lie", artist: "Shakira (feat. Wyclef Jean)", year: 2005, spotifyId: "3ZFTkvIE7kyPt6Nu3PEa7V" },
    { title: "Solo Se Vive una Vez", artist: "Monica Naranjo", year: 1994, spotifyId: "2e7mL0M7mvjYVANfWPUjCH" },
    { title: "La Niña Fresa", artist: "Banda Zeta", year: 1994, spotifyId: "3sgHiiSR5V8V97FiQtne0u" },
    { title: "Me Rehúso", artist: "Danny Ocean", year: 2016, spotifyId: "6ifUES3keWjwXgae8pXI3o" },
    { title: "I'm a Believer", artist: "The Monkees", year: 1966, spotifyId: "3G7tRC24Uh09Hmp1KZ7LQ2" },
    { title: "Dejame Entrar", artist: "Mœnia", year: 1997, spotifyId: "3c1JleEU920IOWJCdqRW0n", aliases: {"artist":["Moenia"]} },
    { title: "Gangsta's Paradise", artist: "Coolio", year: 1995, spotifyId: "1DIXPcTDzTj8ZMHt3PDt8p" },
    { title: "Light My Fire", artist: "The Doors", year: 1967, spotifyId: "5uvosCdMlFdTXhoazkTI5R" },
    { title: "Jailhouse Rock", artist: "Elvis Presley", year: 1958, spotifyId: "4gphxUgq0JSFv2BCLhNDiE" },
    { title: "Propuesta Indecente", artist: "Romeo Santos", year: 2014, spotifyId: "5PycBIeabfvX3n9ILG7Vrv" },
    { title: "Cada Que...", artist: "Belanova", year: 2007, spotifyId: "1IDfAcL63xIRjG4Q98yTfn" },
    { title: "Closer", artist: "The Chainsmokers", year: 2016, spotifyId: "7BKLCZ1jbUBVqRi2FVlTVw" },
    { title: "Crank That (Soulja Boy)", artist: "Soulja Boy", year: 2007, spotifyId: "66TRwr5uJwPt15mfFkzhbi" },
    { title: "La Sirenita", artist: "Rigo Tovar", year: 1976, spotifyId: "6X2Mxz4KnWYOAOHmv3MNAK" },
    { title: "If You Leave Me Now", artist: "Chicago", year: 1976, spotifyId: "0KMGxYKeUzK9wc5DZCt3HT" },
    { title: "Paradise By the Dashboard Light", artist: "Meat Loaf", year: 1977, spotifyId: "2g7gviEeJr6pyxO7G35EWQ" },
    { title: "You Can't Hurry Love", artist: "The Supremes", year: 1966, spotifyId: "4H1iMlEWKZmpKTHCZzDhju" },
    { title: "Se Te Olvida (La Mentira)", artist: "Javier Solís", year: 1963, spotifyId: "0TUtx6LilxwUOtZJKikydZ" },
    { title: "Celebration", artist: "Kool & The Gang", year: 1980, spotifyId: "3K7Q9PHUWPTaknlbFPThn2" },
    { title: "Take A Chance On Me", artist: "ABBA", year: 1977, spotifyId: "5BckPAYcKEJuYs1eV1BHHe" },
    { title: "Because of You", artist: "Kelly Clarkson", year: 2004, spotifyId: "0gJvqi9QyASOCtJu99tytc" },
    { title: "Vive", artist: "José Maria Napoleón", year: 1976, spotifyId: "4YTsQ1axezXF9S6DmX45LS" },
    { title: "¿Donde Están?", artist: "Sentidos Opuestos", year: 1996, spotifyId: "4svFtvFAitlF833rgaDW22" },
    { title: "La de la Mochila Azul", artist: "Pedrito Fernández", year: 1978, spotifyId: "7n1KtrkdGQb2kEOj0M8zVR" },
    { title: "Hey, Soul Sister", artist: "Train", year: 2009, spotifyId: "4HlFJV71xXKIGcU3kRyttv" },
    { title: "Another Brick in the Wall, Pt. 2", artist: "Pink Floyd", year: 1979, spotifyId: "4gMgiXfqyzZLMhsksGmbQV" },
    { title: "Le Freak", artist: "CHIC", year: 1978, spotifyId: "7Kszjzps0xbQXyo1pO4KfE" },
    { title: "Girl, You'll Be A Woman Soon", artist: "Neil Diamond", year: 1968, spotifyId: "1BmVQ5RGqqtF5cnsv6cQYu" },
    { title: "The Middle", artist: "Jimmy Eat World", year: 2001, spotifyId: "6GG73Jik4jUlQCkKg9JuGO" },
    { title: "Yo Quisiera", artist: "Reik", year: 2005, spotifyId: "2GSr8anleCXKLNjjjijoMZ" },
    { title: "Contigo Aprendí", artist: "Armando Manzanero", year: 1967, spotifyId: "7IcqJ3eMGs7pJ1BOCgPSFu" },
    { title: "Johnny B. Goode", artist: "Chuck Berry", year: 1959, spotifyId: "2QfiRTz5Yc8DdShCxG1tB2" },
    { title: "I Wanna Dance with Somebody (Who Loves Me)", artist: "Whitney Houston", year: 1987, spotifyId: "2tUBqZG2AbRi7Q0BIrVrEj" },
    { title: "Waterloo", artist: "ABBA", year: 1974, spotifyId: "3Dy4REq8O09IlgiwuHQ3sk" },
    { title: "Oh, Pretty Woman", artist: "Roy Orbison", year: 1962, spotifyId: "48i055G1OT5KxGGftwFxWy" },
    { title: "(We're Gonna) Rock Around The Clock", artist: "Bill Haley & His Comets", year: 1954, spotifyId: "1uRKT2LRANv4baowBWHfDS" },
    { title: "Tusa", artist: "KAROL G", year: 2019, spotifyId: "7k4t7uLgtOxPwTpFmtJNTY" },
    { title: "Rosa Pastel", artist: "Belanova", year: 2006, spotifyId: "3mU0DbuWtUX5KCaovOQZVK" },
    { title: "La Puerta de Alcalá", artist: "Ana Belén y Victor Manuel", year: 1979, spotifyId: "29opVIw8I1BOZntEn3Un2I" },
    { title: "I Love It", artist: "Icona Pop (feat. Charli XCX)", year: 2012, spotifyId: "2U8NXPTXZWG2O0ye2sYRiH" },
    { title: "Toxic", artist: "Britney Spears", year: 2003, spotifyId: "6I9VzXrHxO9rA9A5euc8Ak" },
    { title: "Funkytown", artist: "Lipps Inc.", year: 2018, spotifyId: "37yIrMPeJYRm7zJ8rr3Uvv" },
    { title: "Umbrella", artist: "Rihanna (feat. Jay-Z)", year: 2007, spotifyId: "2yPoXCs7BSIUrucMdK5PzV" },
    { title: "El 7 de Septiembre", artist: "Mecano", year: 1991, spotifyId: "2fECkGQuw6xt5ObElhbiC1" },
    { title: "Amor Eterno", artist: "Rocío Dúrcal", year: 1984, spotifyId: "2TC4v9YiuQYk3Tk8RH7fV4" },
    { title: "Super Freak", artist: "Rick James", year: 1981, spotifyId: "2dCmGcEOQrMQhMMS8Vj7Ca" },
    { title: "Lamento Boliviano", artist: "Los Enanitos Verdes", year: 1994, spotifyId: "6Pur3hWy6Nzc27ilmsp5HA" },
    { title: "Another Day in Paradise", artist: "Phil Collins", year: 1989, spotifyId: "1NCuYqMc8hKMb4cpNTcJbD" },
    { title: "Bésame Mucho", artist: "Emilio Tuero", year: 1997, spotifyId: "2vgVvWWd6Hsm9ixcttMzSx" },
    { title: "Flowers", artist: "Miley Cyrus", year: 2023, spotifyId: "0yLdNVWF3Srea0uzk55zFn" },
    { title: "MMMBop - Single Version", artist: "Hanson", year: 2006, spotifyId: "2HNZxbvFvasRtlOJ9M6DgR" },
    { title: "Stressed Out", artist: "Twenty One Pilots", year: 2015, spotifyId: "3CRDbSIZ4r5MsZ0YwxuEkn" },
    { title: "Súbete a Mi Moto", artist: "Menudo", year: 1998, spotifyId: "1CNUozOLzsqVQxrct155hY" },
    { title: "Hotel California", artist: "Eagles", year: 1976, spotifyId: "40riOy7x9W7GXjyGp4pjAv" },
    { title: "Dynamite", artist: "BTS", year: 2020, spotifyId: "5QDLhrAOJJdNAmCTJ8xMyW" },
    { title: "Uptown Funk", artist: "Mark Ronson (feat. Bruno Mars)", year: 2015, spotifyId: "32OlwWuMpZ6b0aN2RZOeMS" },
    { title: "Escápate Conmigo", artist: "Wisin (feat. Ozuna)", year: 2017, spotifyId: "1KSqYYJFyfTecXFk9M0prc" },
    { title: "La Bamba - Single Version", artist: "Ritchie Valens", year: 1959, spotifyId: "2aEeghgUcnu75tzcolFMfs" },
    { title: "MIA", artist: "Bad Bunny", year: 2018, spotifyId: "3gE4eQH3K83Sght0ZLvuBK" },
    { title: "El Amante", artist: "Nicky Jam", year: 2017, spotifyId: "3umS4y3uQDkqekNjVpiRUs" },
    { title: "Mi Persona Favorita", artist: "Río Roma", year: 2014, spotifyId: "70fVcEP5pRrxaIICY3DcPe" },
    { title: "Replay", artist: "Iyaz", year: 2009, spotifyId: "5vlEg2fT4cFWAqU5QptIpQ" },
    { title: "What Is Love", artist: "Haddaway", year: 1993, spotifyId: "2IHaGyfxNoFPLJnaEg4GTs" },
    { title: "The Hustle", artist: "Van McCoy", year: 1975, spotifyId: "6hYT9vkr0xMjhBlaLsYq9T" },
    { title: "Ojos Marrones", artist: "Lasso", year: 2022, spotifyId: "7gwT3HGL84vF7bgtwL1N88" },
    { title: "Parchis", artist: "Parchis", year: 1980, spotifyId: "5UiQoY4aSp3cY9V7t6k0S1" },
    { title: "Maneater", artist: "Daryl Hall & John Oates", year: 1982, spotifyId: "7j74lucZ59vqN67Ipe2ZcY" },
    { title: "Bye Bye Bye", artist: "*NSYNC", year: 2000, spotifyId: "62bOmKYxYg7dhrC6gH9vFn", aliases: {"artist":["NSYNC","N Sync"]} },
    { title: "The Lazy Song", artist: "Bruno Mars", year: 2010, spotifyId: "386RUes7n1uM1yfzgeUuwp" },
    { title: "Strangers In The Night", artist: "Frank Sinatra", year: 1966, spotifyId: "74VR3AkGPhbYXnxcOYa16x" },
    { title: "Break My Heart", artist: "Dua Lipa", year: 2020, spotifyId: "017PF4Q3l4DBUiWoXk4OWT" },
    { title: "Marimar", artist: "Thalia", year: 1994, spotifyId: "6NjpVc4lf4yIVns9d0WPNb" },
    { title: "Todos Me Miran", artist: "Gloria Trevi", year: 2006, spotifyId: "4pmRDyDRRiZ5Pq7hm4WTpb" },
    { title: "Payasito (Ponchinello)", artist: "Enrique Guzman", year: 1991, spotifyId: "0bfNMCcujmZHi03rkpFmAL" },
    { title: "La Incondicional", artist: "Luis Miguel", year: 1988, spotifyId: "6F9yAYUaNbUhdlQyt5uZ3b" },
    { title: "En el 2000", artist: "Natalia Lafourcade", year: 2002, spotifyId: "2cVJwPD5CaTx2kBZyomzGN" },
    { title: "Darte un Beso", artist: "Prince Royce", year: 2013, spotifyId: "6cJLfIqwh0tCKRjYM3WpZ5" },
    { title: "La Plaga (Good Golly, Miss Molly)", artist: "Los Teen Tops", year: 1960, spotifyId: "6U4PNy60GmjVdmdMxZxtjB" },
    { title: "Yo no te pido la luna (Non voglio mica la luna)", artist: "Daniela Romo", year: 1984, spotifyId: "09uE7kHv2ESkvtInKugpGM" },
    { title: "Dame Felicidad (Free Me)", artist: "Enrique Guzman", year: 1991, spotifyId: "23phbG3PUXEDUFq0ndNgGq" },
    { title: "Estare", artist: "Kabah", year: 1996, spotifyId: "7H4kdYuy4xwDurVT5zvVuM" },
    { title: "Maldita Primavera", artist: "Yuri", year: 2007, spotifyId: "3GUyiFEglEm9rSToOf5YZW" },
    { title: "As It Was", artist: "Harry Styles", year: 2022, spotifyId: "4LRPiXqCikLlN15c3yImP7" },
    { title: "Pepas", artist: "Farruko", year: 2021, spotifyId: "5fwSHlTEWpluwOM0Sxnh5k" },
    { title: "Lo Que No Fue No Será", artist: "José José", year: 1980, spotifyId: "3nlBG0lCutyuRX3jDRALw0" },
    { title: "Hit the Road Jack", artist: "Ray Charles", year: 1961, spotifyId: "49fzPkBb3aOUWYRKaTWVhm" },
    { title: "Miedo", artist: "Pepe Aguilar", year: 2004, spotifyId: "1ZAkJE2vi1wbo7tyvgWuXN" },
    { title: "In the Mood", artist: "Glenn Miller", year: 1996, spotifyId: "6dZKWYSx5YBIme4SfpIHJ0" },
    { title: "Bella", artist: "Mijares", year: 2004, spotifyId: "4ZIxw3u6TeexXd8rK9DqhL" },
    { title: "Agujetas de Color de Rosa (Pink Shoe Laces)", artist: "Los Hooligans", year: 2007, spotifyId: "4ub7vWkgBWI7fv5DiKPMiA" },
    { title: "Hacer El Amor Con Otro", artist: "Alejandra Guzman", year: 1991, spotifyId: "1OB7cLxxCWA8gbbfjFNNej" },
    { title: "Besos En Guerra", artist: "Morat, Juanes", year: 2017, spotifyId: "1mlGScrDQqHqmhdIqE8MmA" },
    { title: "Yo soy aquél", artist: "Raphael", year: 1967, spotifyId: "4H71d1kJ8DB8J4atO8fbBl" },
    { title: "Summer", artist: "Calvin Harris", year: 2014, spotifyId: "6YUTL4dYpB9xZO5qExPf05" },
    { title: "Viva La Vida", artist: "Coldplay", year: 2008, spotifyId: "3Fcfwhm8oRrBvBZ8KGhtea" },
    { title: "Born To Be Wild", artist: "Steppenwolf", year: 1968, spotifyId: "63OFKbMaZSDZ4wtesuuq6f" },
    { title: "This Love", artist: "Maroon 5", year: 2002, spotifyId: "6ECp64rv50XVz93WvxXMGF" },
    { title: "That Don't Impress Me Much", artist: "Shania Twain", year: 1999, spotifyId: "4I7DV3MIgxJGlObiy9s6nx" },
    { title: "1979", artist: "The Smashing Pumpkins", year: 2001, spotifyId: "3h5zik31hTTat9jmpCZZNC" },
    { title: "Despacito", artist: "Luis Fonsi", year: 2019, spotifyId: "6habFhsOp2NvshLv26DqMb" },
    { title: "Y.M.C.A.", artist: "Village People", year: 1979, spotifyId: "4YOJFyjqh8eAcbKFfv88mV" },
    { title: "En La Intimidad", artist: "Thalia", year: 1991, spotifyId: "5aqKCPNWmlbrZJCEjdSRPy" },
    { title: "Sweet Caroline", artist: "Neil Diamond", year: 1969, spotifyId: "62AuGbAkt8Ox2IrFFb8GKV" },
    { title: "Crazy", artist: "Gnarls Barkley", year: 2006, spotifyId: "2N5zMZX7YeL1tico8oQxa9" },
    { title: "Iris", artist: "The Goo Goo Dolls", year: 1998, spotifyId: "6Qyc6fS4DsZjB2mRW9DsQs" },
    { title: "Que Lloro", artist: "Sin Bandera", year: 2003, spotifyId: "62clthR0fZmLbxeqxVJatQ" },
    { title: "Karma Chameleon", artist: "Culture Club", year: 1983, spotifyId: "5muHy7Z0bHM4uqExt081ue" },
    { title: "Like a Virgin", artist: "Madonna", year: 1984, spotifyId: "1ZPlNanZsJSPK5h9YZZFbZ" },
    { title: "Amorcito corazón", artist: "Pedro Infante", year: 1998, spotifyId: "73WX2V6JVfyQYYIG3K76i8" },
    { title: "How You Remind Me", artist: "Nickelback", year: 2001, spotifyId: "0gmbgwZ8iqyMPmXefof8Yf" },
    { title: "Cómo Te Va Mi Amor", artist: "Pandora", year: 1985, spotifyId: "6Vy53iriyX8Vqx0V68Jzn2" },
    { title: "Crazy", artist: "Aerosmith", year: 1993, spotifyId: "3QxKpdTB8ZSFn8MGeCCpsQ" },
    { title: "Hello", artist: "Adele", year: 2015, spotifyId: "1Yk0cQdMLx5RzzFTYwmuld" },
    { title: "Thunder", artist: "Imagine Dragons", year: 2017, spotifyId: "1zB4vmk8tFRmM9UULNzbLB" },
    { title: "Bésame mucho", artist: "Los Panchos", year: 2018, spotifyId: "7m5p9YuuC8Z9XwS1kYrZFH" },
    { title: "Rosas", artist: "La Oreja de Van Gogh", year: 2003, spotifyId: "4waqcUQWdj0yH26STWl2Rq" },
    { title: "Cómo Te Voy A Olvidar", artist: "Los Ángeles Azules", year: 1996, spotifyId: "51dNexiESqcJLsGLrmg1Nv" },
    { title: "Take Me Home, Country Roads", artist: "John Denver", year: 1971, spotifyId: "1YYhDizHx7PnDhAhko6cDS" },
    { title: "Estoy Pensando en Ti", artist: "La Sonora Santanera", year: 1968, spotifyId: "1X2VZSug0EnkzDqVSin47F" },
    { title: "Sugar", artist: "Maroon 5", year: 2014, spotifyId: "2iuZJX9X9P0GKaE93xcPjk" },
    { title: "Everybody Hurts", artist: "R.E.M.", year: 1992, spotifyId: "6PypGyiu0Y2lCDBN1XZEnP", aliases: {"artist":["REM"]} },
    { title: "Soy Yo", artist: "Bomba Estéreo", year: 2015, spotifyId: "4Egb5xP6cniUx0kgZd5zLB" },
    { title: "La Interesada", artist: "Chava Flores", year: 1962, spotifyId: "5UbjsmHa2M69q2Q1bzmDBE" },
    { title: "Get Lucky", artist: "Daft Punk (feat. Pharrell Williams and Nile Rodgers)", year: 2013, spotifyId: "69kOkLUCkxIZYexIgSG8rq" },
    { title: "El Reloj", artist: "Los Tres Caballeros", year: 1957, spotifyId: "27u17peWruKyUe7RfBglZC" },
    { title: "Cien años", artist: "Pedro Infante", year: 1954, spotifyId: "760r2LXNtMaHDKMQ5wkXbi" },
    { title: "Silly Love Songs", artist: "Wings", year: 1976, spotifyId: "5Qhfo6ZqoA2oPF5uFf43L3" },
    { title: "November Rain", artist: "Guns N' Roses", year: 1991, spotifyId: "3YRCqOhFifThpSRFJ1VWFM" },
    { title: "Disco Inferno", artist: "The Trammps", year: 1976, spotifyId: "5jUA1njy3h6ynHLvPdEVHt" },
    { title: "My Heart Will Go On - Love Theme from \"Titanic\"", artist: "Céline Dion", year: 1997, spotifyId: "33LC84JgLvK2KuW43MfaNq" },
    { title: "Heart Of Glass", artist: "Blondie", year: 1978, spotifyId: "41AE8ODX2JETBCa6muhSLY" },
    { title: "Señorita", artist: "Shawn Mendes", year: 2019, spotifyId: "0TK2YIli7K1leLovkQiNik" },
    { title: "bad guy", artist: "Billie Eilish", year: 2019, spotifyId: "2Fxmhks0bxGSBdJ92vM42m" },
    { title: "Blinding Lights", artist: "The Weeknd", year: 2019, spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
    { title: "Vogue", artist: "Madonna", year: 1990, spotifyId: "7j5TIXPi0cCbSSqItmbyZy" },
    { title: "Zombie", artist: "The Cranberries", year: 1994, spotifyId: "7EZC6E7UjZe63f1jRmkWxt" },
    { title: "Let Her Cry", artist: "Hootie & The Blowfish", year: 1994, spotifyId: "6NGi23FFKq9tH5NR1NcTw2" },
    { title: "Flashdance...What a Feeling - Radio Edit", artist: "Irene Cara", year: 1983, spotifyId: "3cbV252akVZInSvJk7jAYX" },
    { title: "Don't Turn Around", artist: "Ace of Base", year: 1993, spotifyId: "4SYMibQ93bfzOk6uzkF0dO" },
    { title: "Muriendo Lento", artist: "Timbiriche", year: 1993, spotifyId: "1qqk4LVn8q3kJBjDcXkTGh" },
    { title: "La Chica de Humo", artist: "Emmanuel", year: 1989, spotifyId: "0GZ8UVlhn2tjHPpngzoLJk" },
    { title: "Sexo Pudor Y Lágrimas", artist: "Aleks Syntek", year: 1999, spotifyId: "27qjcww3SKGeD4wTUOJEeh" },
    { title: "Scars To Your Beautiful", artist: "Alessia Cara", year: 2016, spotifyId: "42ydLwx4i5V49RXHOozJZq" },
    { title: "Need You Tonight", artist: "INXS", year: 1987, spotifyId: "5eU8qMd0TpaLqTGDZJaLDs" },
    { title: "No Role Modelz", artist: "J. Cole", year: 2014, spotifyId: "68Dni7IE4VyPkTOH9mRWHr" },
    { title: "Get Back", artist: "The Beatles", year: 1969, spotifyId: "4MLBqAEzNN89o2M9h92Z26" },
    { title: "Mona Lisa", artist: "Nat King Cole", year: 1950, spotifyId: "5dae01pKNjRQtgOeAkFzPY" },
    { title: "Wonderwall", artist: "Oasis", year: 1995, spotifyId: "1qPbGZqppFwLwcBC1JQ6Vr" },
    { title: "I Shot The Sheriff", artist: "Eric Clapton", year: 1974, spotifyId: "0UOxp1BpnD8uPQMKU4wKjz" },
    { title: "Mambo No. 8", artist: "Pérez Prado", year: 1949, spotifyId: "7gvrntH4fFWZWKwpPLWjgw" },
    { title: "Mon amour", artist: "zzoilo", year: 2020, spotifyId: "064ikblBFGS6HL35D71LZy" },
    { title: "Wrecking Ball", artist: "Miley Cyrus", year: 2013, spotifyId: "2vwlzO0Qp8kfEtzTsCXfyE" },
    { title: "Don't Stop Believin'", artist: "Journey", year: 1981, spotifyId: "4bHsxqR3GMrXTxEPLuK5ue" },
    { title: "Since U Been Gone", artist: "Kelly Clarkson", year: 2004, spotifyId: "3xrn9i8zhNZsTtcoWgQEAd" },
    { title: "Los Malaventurados No Lloran", artist: "PXNDX", year: 2006, spotifyId: "66PRDvzBHhbcdbc4T4mrZY", aliases: {"artist":["Panda"]} },
    { title: "All That She Wants", artist: "Ace of Base", year: 1993, spotifyId: "6kWJvPfC4DgUpRsXKNa9z9" },
    { title: "Mi soledad y yo", artist: "Alejandro Sanz", year: 1995, spotifyId: "3GFLbBgMuY2RELNo6tMqOS" },
    { title: "Surfin' U.S.A.", artist: "The Beach Boys", year: 1963, spotifyId: "2dbaIpJoAk2hhrrX2ljKJo" },
    { title: "A quien tú decidiste amar", artist: "Sandoval", year: 2009, spotifyId: "3lJwIAfeWtnNRbJXWbIHKD" },
    { title: "Love Me Like You Do", artist: "Ellie Goulding", year: 2015, spotifyId: "3zHq9ouUJQFQRf3cm1rRLu" },
    { title: "Mr. Jones", artist: "Counting Crows", year: 1993, spotifyId: "5DiXcVovI0FcY2s0icWWUu" },
    { title: "Sk8er Boi", artist: "Avril Lavigne", year: 2002, spotifyId: "00Mb3DuaIH1kjrwOku9CGU" },
    { title: "Un Alma en Pena", artist: "Lucía Méndez", year: 2011, spotifyId: "19a0LWL0uI0ggevU7QpzpG" },
    { title: "Baby", artist: "Justin Bieber", year: 2010, spotifyId: "6epn3r7S14KUqlReYr77hA" },
    { title: "Devuélveme a mi chica", artist: "Hombres G", year: 1985, spotifyId: "1Wrzhfa5bNlqvsnCztz190" },
    { title: "Ice Ice Baby", artist: "Vanilla Ice", year: 1990, spotifyId: "11d9oUiwHuYt216EFA2tiz" },
    { title: "STAY", artist: "The Kid LAROI & Justin Bieber", year: 2021, spotifyId: "5HCyWlXZPP0y6Gqq8TgA20" },
    { title: "SexyBack", artist: "Justin Timberlake (feat. Timbaland)", year: 2006, spotifyId: "0O45fw2L5vsWpdsOdXwNAR" },
    { title: "Donde Estas Corazon", artist: "Shakira", year: 1995, spotifyId: "6IGvaQ4aFBjy66TdUurIiA" },
    { title: "Adiós Amor", artist: "Christian Nodal", year: 2017, spotifyId: "63bmZnBN1CiJ9sA4qTEe8y" },
    { title: "Sugar, Sugar", artist: "The Archies", year: 1969, spotifyId: "3iSws76HjaU7k49EqJVTfF" },
    { title: "INDUSTRY BABY", artist: "Lil Nas X (feat. Jack Harlow)", year: 2021, spotifyId: "27NovPIUIRrOZoCHxABJwK" },
    { title: "The Locomotion", artist: "Little Eva", year: 1962, spotifyId: "5xzdDMhFYiuUONB0Mha9VS" },
    { title: "María Bonita", artist: "Agustín Lara", year: 2001, spotifyId: "6eD6RGKhnI6AZhGPRXMGGd" },
    { title: "La Bikina", artist: "Juan Torres", year: 1964, spotifyId: "1CTWQpPUhy1hlqd1GGzO3O" },
    { title: "Kilómetros", artist: "Sin Bandera", year: 2002, spotifyId: "1AfAFpHJ7s4unBIhe3NM5j" },
    { title: "Somebody That I Used to Know", artist: "Gotye (feat. Kimbra)", year: 2011, spotifyId: "62oaDoBveZxvZb94ziiMXi" },
    { title: "Favorito", artist: "Camilo", year: 2020, spotifyId: "0Snbzbd74RLfL0i4nn1vU5" },
    { title: "Take on Me", artist: "a-ha", year: 1985, spotifyId: "2WfaOiMkCvy7F5fcp2zZ8L", aliases: {"artist":["Aha"]} },
    { title: "Desesperada", artist: "Marta Sánchez", year: 1993, spotifyId: "20WaSPMyeIO7NntPpn1FM5" },
    { title: "Anti-Hero", artist: "Taylor Swift", year: 2022, spotifyId: "0V3wPSX9ygBnCm8psDIegu" },
    { title: "Genie In A Bottle", artist: "Christina Aguilera", year: 1999, spotifyId: "11mwFrKvLXCbcVGNxffGyP" },
    { title: "Price Tag", artist: "Jessie J (feat. B.O.B)", year: 2011, spotifyId: "2fTsFCKRFQ5M0igJgabnLA" },
    { title: "Dancing Queen", artist: "ABBA", year: 1976, spotifyId: "0GjEhVFGZW8afUYGChu3Rr" },
    { title: "Every Breath You Take", artist: "The Police", year: 1983, spotifyId: "1JSTJqkT5qHq8MDJnJbRE1" },
    { title: "Bitter Sweet Symphony", artist: "The Verve", year: 1997, spotifyId: "1WYEDcS7WGjv0rG7rmMX3o" },
    { title: "Cheap Thrills", artist: "Sia", year: 2016, spotifyId: "27SdWb2rFzO6GWiYDBTD9j" },
];
